apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-pvc-creation
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8-pvc-creation
  template:
    metadata:
     labels:
       app.kubernetes.io/name: k8-pvc-creation
    spec:
      serviceAccountName: k8-pvc-creation
      containers:
        - name: k8-pvc-creation
          image: docker.io/dhasuda/k8-pvc-creation:latest
---
apiVersion: v1
kind: Service
metadata:
  name: k8-pvc-creation
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: k8-pvc-creation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8-pvc-creation
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8-pvc-creation-binding
subjects:
  - kind: ServiceAccount
    name: k8-pvc-creation
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-secrets
  